---
abstract: 'interact with a Cisco router'
author:
  - 'Joshua Keroes (joshua@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Telnet-Cisco
no_index:
  directory:
    - t
    - inc
requires:
  Net::Telnet: '3.02'
  Test::More: '0'
version: '1.11'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
